---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  - name: windows
    box: gusztavvargadr/windows-server
    cpus: 2
    memory: 4096
    interfaces:
      - auto_config: true
        ip: 172.28.128.3
        network_name: private_network
        type: static
provisioner:
  name: ansible
  log: true
  inventory:
    host_vars:
      windows:
        ansible_become: false
        ansible_connection: winrm
        ansible_host: 127.0.0.1
        ansible_password: vagrant
        ansible_port: 55985
        ansible_user: vagrant
        ansible_winrm_scheme: http
        ansible_winrm_transport: basic

        ad_organizational_units:
          - { name: garage, path: "DC=INTERNAL,DC=NOEG,DC=WTF" }
          - { name: users, path: "OU=garage,DC=INTERNAL,DC=NOEG,DC=WTF"}
          - { name: groups, path: "OU=garage,DC=INTERNAL,DC=NOEG,DC=WTF"}
          - { name: computers, path: "OU=garage,DC=INTERNAL,DC=NOEG,DC=WTF"}
          - { name: svc, path: "OU=garage,DC=INTERNAL,DC=NOEG,DC=WTF"}
        ad_users:
          - { username: noe, path: "OU=users,OU=garage,DC=INTERNAL,DC=NOEG,DC=WTF" }
          - { username: rancher, path: "OU=svc,OU=garage,DC=INTERNAL,DC=NOEG,DC=WTF" }
          - { username: spinnaker, path: "OU=svc,OU=garage,DC=INTERNAL,DC=NOEG,DC=WTF" }


  lint:
    name: ansible-lint
    options:
      x: [
        "204"  # Lines should be no longer than 160 chars
      ]
verifier:
  name: testinfra
  lint:
    name: flake8
